server {
    listen 3000;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip settings
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Serve static files, fallback to index.html for Single Page Application routing
        try_files $uri $uri/ /index.html;
    }

    # Disabled caching for development
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
        try_files $uri =404;
    }
}
