"use client"

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import {
    LineChart,
    Line,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
    Legend
} from 'recharts'
import { ShieldCheck, Target, Activity, CheckCircle, Database, ThumbsUp } from 'lucide-react'
import { getEvaluationMetrics, getLatestEvaluations, LatestEvaluations, EvaluationMetricRun } from '@/lib/api'

export default function EvaluationsDashboard() {
    const [latest, setLatest] = useState<LatestEvaluations | null>(null)
    const [history, setHistory] = useState<EvaluationMetricRun[]>([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)
    const [dataSource, setDataSource] = useState<string>("loading")

    useEffect(() => {
        async function load() {
            try {
                const [latestData, historyData] = await Promise.all([
                    getLatestEvaluations(),
                    getEvaluationMetrics(20)
                ])
                setLatest(latestData)

                // Format history for Recharts
                // Need to merge points by timestamp or just plot them individually 
                // formatted by date string
                const formattedHistory = historyData.data.map(run => ({
                    ...run,
                    dateLabel: new Date(run.timestamp).toLocaleDateString() + ' ' + new Date(run.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                    // Flatten metrics for charting
                    faithfulness: run.metrics.faithfulness || undefined,
                    answer_relevancy: run.metrics.answer_relevancy || undefined,
                    context_precision: run.metrics.context_precision || undefined,
                    precision: run.metrics.precision || undefined,
                    recall: run.metrics.recall || undefined,
                })).reverse() // Chronological order for chart

                setHistory(formattedHistory)
                setDataSource(historyData.source)
            } catch (err: any) {
                setError(err.message || 'Failed to load evaluation metrics')
            } finally {
                setLoading(false)
            }
        }
        load()
    }, [])


    // Chart Custom Tooltip
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const CustomTooltip = ({ active, payload, label }: any) => {
        if (active && payload && payload.length) {
            return (
                <div className="bg-black/90 border border-white/10 p-4 rounded-xl shadow-2xl backdrop-blur-md text-sm">
                    <p className="text-white/60 mb-2">{label}</p>
                    {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                    {payload.map((entry: any, index: number) => (
                        <div key={index} className="flex items-center gap-2 mb-1">
                            <div className="w-2 h-2 rounded-full" style={{ backgroundColor: entry.color }} />
                            <span className="text-white capitalize">{entry.name.replace('_', ' ')}:</span>
                            <span className="text-white font-mono ml-auto">
                                {Number(entry.value).toFixed(3)}
                            </span>
                        </div>
                    ))}
                </div>
            );
        }
        return null;
    };


    if (loading) {
        return (
            <div className="flex h-full items-center justify-center">
                <div className="h-8 w-8 animate-spin rounded-full border-4 border-white/20 border-t-white" />
            </div>
        )
    }

    const ragasMetrics = latest?.ragas?.metrics || {}
    const adjMetrics = latest?.adjudicator?.metrics || {}
    const csatData = latest?.csat || null

    return (
        <div className="max-w-7xl mx-auto p-8 pt-24 min-h-screen">
            <div className="mb-8 flex justify-between items-end">
                <div>
                    <h1 className="text-4xl font-bold bg-gradient-to-r from-white to-white/60 bg-clip-text text-transparent inline-flex items-center gap-3">
                        <ShieldCheck className="w-10 h-10 text-emerald-500" />
                        Evaluation Analytics
                    </h1>
                    <p className="text-white/60 mt-2 max-w-2xl">
                        Deterministic safety and accuracy metrics generated by the RAGAS framework and Adversarial Safety Adjudicator.
                    </p>
                </div>

                <div className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-full text-xs text-white/60">
                    <Database className="w-3 h-3" />
                    Source: <span className="text-white capitalize">{dataSource.replace('_', ' ')}</span>
                </div>
            </div>

            {error && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl mb-8">
                    {error}
                </div>
            )}

            {/* KPI Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 mb-8">
                <MetricCard
                    title="Faithfulness"
                    value={ragasMetrics.faithfulness}
                    target={0.95}
                    icon={<Target className="w-5 h-5 text-blue-400" />}
                    desc="Measures if the answer is completely derived from context without hallucination."
                />
                <MetricCard
                    title="Answer Relevancy"
                    value={ragasMetrics.answer_relevancy}
                    target={0.85}
                    icon={<Activity className="w-5 h-5 text-purple-400" />}
                    desc="Measures how well the answer addresses the specific clinical question."
                />
                <MetricCard
                    title="Adjudicator Precision"
                    value={adjMetrics.precision}
                    target={0.90}
                    icon={<ShieldCheck className="w-5 h-5 text-emerald-400" />}
                    desc="Accuracy of the Red Team model in flagging truly dangerous answers."
                />
                <MetricCard
                    title="Adjudicator Recall"
                    value={adjMetrics.recall}
                    target={0.95}
                    icon={<CheckCircle className="w-5 h-5 text-rose-400" />}
                    desc="Critical safety metric: ability to catch all dangerous medical advice."
                />
                <MetricCard
                    title="Clinical Approval (CSAT)"
                    value={csatData?.score ?? undefined}
                    target={0.80}
                    icon={<ThumbsUp className="w-5 h-5 text-blue-400" />}
                    desc={`Doctor thumbs up / total ratings. Based on ${csatData?.total_ratings || 0} reviews.`}
                />
            </div>

            {/* Charts Area */}
            {history.length > 0 ? (
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-8 mb-8">
                    {/* RAGAS Chart */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="bg-[#0a0a0a] border border-white/5 p-6 rounded-2xl relative overflow-hidden"
                    >
                        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-purple-500 opacity-50" />
                        <h3 className="text-lg font-semibold text-white mb-6">RAG Pipeline Metrics (Time Series)</h3>
                        <div className="h-[300px] w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <LineChart data={history.filter(h => h.evaluation_type === 'ragas')}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
                                    <XAxis dataKey="dateLabel" stroke="#ffffff40" fontSize={12} tickMargin={10} minTickGap={30} />
                                    <YAxis stroke="#ffffff40" fontSize={12} domain={[0, 1]} tickFormatter={(v) => v.toFixed(2)} />
                                    <Tooltip content={<CustomTooltip />} />
                                    <Legend iconType="circle" wrapperStyle={{ fontSize: '12px', opacity: 0.8 }} />
                                    <Line type="monotone" dataKey="faithfulness" stroke="#60a5fa" strokeWidth={3} dot={{ r: 4, fill: "#0a0a0a", strokeWidth: 2 }} activeDot={{ r: 6 }} />
                                    <Line type="monotone" dataKey="answer_relevancy" stroke="#c084fc" strokeWidth={3} dot={{ r: 4, fill: "#0a0a0a", strokeWidth: 2 }} activeDot={{ r: 6 }} />
                                    <Line type="monotone" dataKey="context_precision" stroke="#fb923c" strokeWidth={2} strokeDasharray="5 5" dot={false} />
                                </LineChart>
                            </ResponsiveContainer>
                        </div>
                    </motion.div>

                    {/* Adjudicator Chart */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1 }}
                        className="bg-[#0a0a0a] border border-white/5 p-6 rounded-2xl relative overflow-hidden"
                    >
                        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-emerald-500 to-rose-500 opacity-50" />
                        <h3 className="text-lg font-semibold text-white mb-6">Safety Adjudicator Evaluation (Time Series)</h3>
                        <div className="h-[300px] w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <LineChart data={history.filter(h => h.evaluation_type === 'adjudicator')}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
                                    <XAxis dataKey="dateLabel" stroke="#ffffff40" fontSize={12} tickMargin={10} minTickGap={30} />
                                    <YAxis stroke="#ffffff40" fontSize={12} domain={[0, 1]} tickFormatter={(v) => v.toFixed(2)} />
                                    <Tooltip content={<CustomTooltip />} />
                                    <Legend iconType="circle" wrapperStyle={{ fontSize: '12px', opacity: 0.8 }} />
                                    <Line type="monotone" dataKey="precision" name="Precision" stroke="#34d399" strokeWidth={3} dot={{ r: 4, fill: "#0a0a0a", strokeWidth: 2 }} activeDot={{ r: 6 }} />
                                    <Line type="monotone" dataKey="recall" name="Recall (Safety Critical)" stroke="#fb7185" strokeWidth={3} dot={{ r: 4, fill: "#0a0a0a", strokeWidth: 2 }} activeDot={{ r: 6 }} />
                                </LineChart>
                            </ResponsiveContainer>
                        </div>
                    </motion.div>
                </div>
            ) : (
                <div className="bg-white/5 border border-white/10 rounded-2xl p-12 text-center">
                    <Database className="w-12 h-12 text-white/20 mx-auto mb-4" />
                    <h3 className="text-xl text-white font-medium mb-2">No Evaluation History Found</h3>
                    <p className="text-white/50 max-w-md mx-auto">
                        Run the evaluation scripts (`evaluate_ragas.py` or `evaluate_adjudicator.py`) to generate metrics that will appear here.
                    </p>
                </div>
            )}
        </div>
    )
}

function MetricCard({ title, value, target, icon, desc }: { title: string, value: number | undefined, target: number, icon: React.ReactNode, desc: string }) {
    const isPassing = value !== undefined && value >= target;
    const isMarginal = value !== undefined && value >= target - 0.05 && value < target;

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className={`p-6 rounded-2xl border ${value === undefined ? 'border-white/5 bg-[#0a0a0a]' :
                isPassing ? 'border-emerald-500/20 bg-emerald-500/5' :
                    isMarginal ? 'border-yellow-500/20 bg-yellow-500/5' :
                        'border-rose-500/20 bg-rose-500/5'
                } transition-colors duration-300 relative overflow-hidden group`}
        >
            <div className="flex justify-between items-start mb-4">
                <div className="p-2 bg-white/5 rounded-lg border border-white/10">{icon}</div>
                {value !== undefined && (
                    <div className={`text-xs px-2 py-1 rounded-full border ${isPassing ? 'border-emerald-500/30 text-emerald-400 bg-emerald-500/10' : (isMarginal ? 'border-yellow-500/30 text-yellow-400 bg-yellow-500/10' : 'border-rose-500/30 text-rose-400 bg-rose-500/10')}`}>
                        {isPassing ? 'PASS' : isMarginal ? 'MARGINAL' : 'FAIL'}
                    </div>
                )}
            </div>

            <h3 className="text-white/60 text-sm font-medium mb-1">{title}</h3>
            <div className="text-3xl font-bold text-white mb-2 font-mono">
                {value !== undefined ? value.toFixed(3) : '---'}
            </div>

            <div className="text-xs text-white/40 flex justify-between items-center">
                <span>Target: {target.toFixed(2)}+</span>
            </div>

            {/* Hover tooltip for description */}
            <div className="absolute inset-0 bg-[#0a0a0a] p-6 opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex flex-col justify-center">
                <h4 className="text-white text-sm font-semibold mb-2">{title}</h4>
                <p className="text-white/60 text-xs leading-relaxed">{desc}</p>
            </div>
        </motion.div>
    )
}
