#!/usr/bin/env python3
"""
Grounded generation evaluator for the synthetic clinical QA benchmark.

This evaluator is intentionally separate from retrieval evaluation. It scores
final answers against required evidence chunks, citation behavior, abstention
behavior, and deterministic keyword-based completeness checks.
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DATASET = REPO_ROOT / "backend" / "data" / "synthetic_clinical_qa_180.jsonl"
DEFAULT_OUTPUT = REPO_ROOT / "results" / "grounded_generation_evaluation_results.json"
EVALUATOR_SELF_TEST_DISCLOSURE = (
    "Offline grounded-generation scores are evaluator infrastructure self-tests only. "
    "They are generated by feeding expected answers and expected citations back into the evaluator. "
    "They do not measure LLM answer quality."
)

ABSTENTION_MARKERS = (
    "abstain",
    "not enough evidence",
    "insufficient evidence",
    "cannot answer",
    "outside the available",
    "conflicting",
    "does not contain",
)

CITATION_PATTERN = re.compile(r"\[([A-Za-z0-9_.:/-]+)\]")
SENTENCE_PATTERN = re.compile(r"(?<=[.!?])\s+")
CLAIM_SPLIT_PATTERN = re.compile(r"\s*;\s*")
TOKEN_PATTERN = re.compile(r"[a-zA-Z][a-zA-Z0-9%./-]*|\d+(?:\.\d+)?%?")
NUMBER_PATTERN = re.compile(r"\b\d+(?:\.\d+)?%?\b")

CLAIM_STOPWORDS = {
    "a",
    "an",
    "and",
    "appropriate",
    "are",
    "as",
    "at",
    "be",
    "because",
    "by",
    "case",
    "clinical",
    "documented",
    "does",
    "for",
    "from",
    "has",
    "have",
    "in",
    "is",
    "it",
    "later",
    "not",
    "of",
    "on",
    "or",
    "patient",
    "provided",
    "record",
    "remains",
    "review",
    "same",
    "should",
    "source",
    "the",
    "this",
    "to",
    "was",
    "were",
    "whether",
    "with",
}


@dataclass(frozen=True)
class AtomicClaim:
    text: str
    citation_ids: tuple[str, ...]


class ClaimVerifier(Protocol):
    """Interface for deterministic, NLI, or LLM-backed claim verification."""

    def verify(self, answer: str, case: dict[str, Any]) -> list[dict[str, Any]]:
        ...


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    cases: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            data = json.loads(line)
            required = {
                "id",
                "question",
                "expected_answer",
                "required_evidence_chunks",
                "evidence_chunks",
                "scope",
                "difficulty",
                "failure_mode_category",
                "should_answer",
            }
            missing = sorted(required - set(data))
            if missing:
                raise ValueError(f"{path}:{line_number} is missing required fields: {', '.join(missing)}")
            cases.append(data)
    return cases


def load_answers(path: Path) -> dict[str, str]:
    answers: dict[str, str] = {}
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            row = json.loads(line)
            case_id = row.get("id") or row.get("case_id")
            answer = row.get("answer") or row.get("generated_answer")
            if not case_id or answer is None:
                raise ValueError(f"{path}:{line_number} must include id and answer")
            answers[str(case_id)] = str(answer)
    return answers


def mock_answer(case: dict[str, Any]) -> str:
    citations = " ".join(f"[{chunk_id}]" for chunk_id in case["required_evidence_chunks"])
    if case["should_answer"]:
        return f"{case['expected_answer']} {citations}".strip()
    if case["required_evidence_chunks"]:
        return f"{case['expected_answer']} {citations}".strip()
    return case["expected_answer"]


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().lower()


def is_abstention(answer: str) -> bool:
    lowered = normalize(answer)
    return any(marker in lowered for marker in ABSTENTION_MARKERS)


def extract_citations(answer: str) -> list[str]:
    return CITATION_PATTERN.findall(answer)


def split_claims(answer: str) -> list[str]:
    return [claim.text for claim in extract_atomic_claims(answer)]


def extract_atomic_claims(answer: str) -> list[AtomicClaim]:
    claims: list[AtomicClaim] = []
    for sentence in SENTENCE_PATTERN.split(answer):
        if not sentence.strip():
            continue
        sentence_citations = tuple(extract_citations(sentence))
        clean_sentence = CITATION_PATTERN.sub("", sentence).strip()
        if not clean_sentence and sentence_citations and claims:
            previous = claims[-1]
            claims[-1] = AtomicClaim(
                text=previous.text,
                citation_ids=tuple(dict.fromkeys((*previous.citation_ids, *sentence_citations))),
            )
            continue
        if not clean_sentence:
            continue
        for part in CLAIM_SPLIT_PATTERN.split(clean_sentence):
            text = part.strip(" .")
            if len(text.split()) < 2:
                continue
            claims.append(AtomicClaim(text=text, citation_ids=sentence_citations))
    return claims


def tokenize_for_support(text: str) -> set[str]:
    tokens = {token.lower() for token in TOKEN_PATTERN.findall(text)}
    return {token for token in tokens if len(token) > 1 and token not in CLAIM_STOPWORDS}


def _best_evidence_matches(claim_tokens: set[str], evidence_chunks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    matches: list[dict[str, Any]] = []
    if not claim_tokens:
        return matches
    for chunk in evidence_chunks:
        evidence_tokens = tokenize_for_support(str(chunk.get("text", "")))
        overlap = sorted(claim_tokens & evidence_tokens)
        score = len(overlap) / max(1, len(claim_tokens))
        matches.append(
            {
                "chunk_id": chunk.get("chunk_id"),
                "support_score": score,
                "overlap_terms": overlap,
            }
        )
    return sorted(matches, key=lambda item: item["support_score"], reverse=True)


def _combined_evidence_score(claim_tokens: set[str], evidence_chunks: list[dict[str, Any]]) -> float:
    if not claim_tokens or not evidence_chunks:
        return 0.0
    evidence_tokens: set[str] = set()
    for chunk in evidence_chunks:
        evidence_tokens.update(tokenize_for_support(str(chunk.get("text", ""))))
    return len(claim_tokens & evidence_tokens) / max(1, len(claim_tokens))


class HeuristicClaimVerifier:
    """Deterministic lexical verifier used when no NLI/LLM verifier is configured."""

    support_threshold = 0.42

    def verify(self, answer: str, case: dict[str, Any]) -> list[dict[str, Any]]:
        evidence_by_id = {chunk["chunk_id"]: chunk for chunk in case.get("evidence_chunks", [])}
        forbidden = case.get("forbidden_keywords", [])
        claims = extract_atomic_claims(answer)
        results: list[dict[str, Any]] = []

        for claim in claims:
            result = self._verify_claim(claim, case, evidence_by_id, forbidden)
            results.append(result)
        return results

    def _verify_claim(
        self,
        claim: AtomicClaim,
        case: dict[str, Any],
        evidence_by_id: dict[str, dict[str, Any]],
        forbidden_keywords: list[str],
    ) -> dict[str, Any]:
        valid_cited_chunks = [evidence_by_id[citation_id] for citation_id in claim.citation_ids if citation_id in evidence_by_id]
        unknown_citations = [citation_id for citation_id in claim.citation_ids if citation_id not in evidence_by_id]
        candidate_chunks = valid_cited_chunks or list(evidence_by_id.values())
        claim_tokens = tokenize_for_support(claim.text)
        matches = _best_evidence_matches(claim_tokens, candidate_chunks)
        mapped = [match for match in matches[:3] if match["support_score"] > 0]
        best_score = max(matches[0]["support_score"] if matches else 0.0, _combined_evidence_score(claim_tokens, candidate_chunks))

        claim_lower = normalize(claim.text)
        forbidden_matches = [keyword for keyword in forbidden_keywords if normalize(keyword) in claim_lower]
        if forbidden_matches:
            status = "contradicted"
            rationale = f"Claim contains forbidden or contradicted assertion: {', '.join(forbidden_matches)}"
        elif unknown_citations and not valid_cited_chunks:
            status = "unverifiable"
            rationale = f"Claim cites unknown evidence chunks: {', '.join(unknown_citations)}"
        elif self._is_supported_abstention_claim(claim.text, case):
            status = "supported"
            rationale = "Abstention claim is consistent with the expected no-answer case."
        elif self._has_negation_conflict(claim.text, valid_cited_chunks or list(evidence_by_id.values())):
            status = "contradicted"
            rationale = "Claim polarity conflicts with the mapped evidence."
        elif self._has_numeric_mismatch(claim.text, candidate_chunks):
            status = "unsupported"
            rationale = "Claim contains a numeric value that is not present in the mapped evidence."
        elif best_score >= self.support_threshold:
            status = "supported"
            rationale = f"Mapped evidence overlaps enough clinical terms (score={best_score:.2f})."
        elif candidate_chunks:
            status = "unsupported"
            rationale = f"Mapped evidence is present but does not support the claim (score={best_score:.2f})."
        else:
            status = "unverifiable"
            rationale = "No evidence chunks are available for this claim."

        return {
            "claim": claim.text,
            "citation_ids": list(claim.citation_ids),
            "mapped_evidence_chunks": mapped,
            "status": status,
            "support_score": best_score,
            "unknown_citations": unknown_citations,
            "rationale": rationale,
        }

    def _is_supported_abstention_claim(self, claim_text: str, case: dict[str, Any]) -> bool:
        if case.get("should_answer", True):
            return False
        lowered = normalize(claim_text)
        return any(marker in lowered for marker in ABSTENTION_MARKERS)

    def _has_negation_conflict(self, claim_text: str, chunks: list[dict[str, Any]]) -> bool:
        claim_lower = normalize(claim_text)
        evidence_text = " ".join(normalize(str(chunk.get("text", ""))) for chunk in chunks)
        if "no known drug allergies" in claim_lower and ("allergy" in evidence_text or "causes hives" in evidence_text):
            return True
        if "safe to prescribe" in claim_lower and ("allergy" in evidence_text or "causes hives" in evidence_text):
            return True
        if "no " in claim_lower and any(term in evidence_text for term in ("elevated", "increased", "positive", "causes hives")):
            return True
        return False

    def _has_numeric_mismatch(self, claim_text: str, chunks: list[dict[str, Any]]) -> bool:
        claim_numbers = set(NUMBER_PATTERN.findall(claim_text))
        if not claim_numbers:
            return False
        evidence_text = " ".join(str(chunk.get("text", "")) for chunk in chunks)
        evidence_numbers = set(NUMBER_PATTERN.findall(evidence_text))
        if not evidence_numbers:
            return False
        return not claim_numbers <= evidence_numbers


def claim_status_counts(claim_results: list[dict[str, Any]]) -> dict[str, int]:
    counts = {"supported": 0, "unsupported": 0, "contradicted": 0, "unverifiable": 0}
    for claim in claim_results:
        status = claim.get("status")
        if status in counts:
            counts[status] += 1
    return counts


def keyword_coverage(answer: str, keywords: list[str]) -> float:
    if not keywords:
        return 1.0
    lowered = normalize(answer)
    found = sum(1 for keyword in keywords if normalize(keyword) in lowered)
    return found / len(keywords)


def forbidden_hits(answer: str, forbidden_keywords: list[str]) -> list[str]:
    lowered = normalize(answer)
    return [keyword for keyword in forbidden_keywords if normalize(keyword) in lowered]


def score_case(case: dict[str, Any], answer: str, verifier: ClaimVerifier | None = None) -> dict[str, Any]:
    verifier = verifier or HeuristicClaimVerifier()
    required = set(case["required_evidence_chunks"])
    available = {chunk["chunk_id"] for chunk in case["evidence_chunks"]}
    cited = extract_citations(answer)
    cited_set = set(cited)
    cited_required = cited_set & required
    cited_unknown = cited_set - available

    if cited:
        citation_precision = len(cited_required) / len(cited_set)
    else:
        citation_precision = 1.0 if not required else 0.0

    if required:
        citation_recall = len(cited_required) / len(required)
    else:
        citation_recall = 1.0 if not cited else 0.0

    abstained = is_abstention(answer)
    should_answer = bool(case["should_answer"])
    abstention_correct = (not should_answer and abstained) or (should_answer and not abstained)
    completeness = keyword_coverage(answer, case.get("expected_keywords", []))
    forbidden = forbidden_hits(answer, case.get("forbidden_keywords", []))

    claim_results = verifier.verify(answer, case)
    status_counts = claim_status_counts(claim_results)
    claim_count = max(1, len(claim_results))
    unsupported_claim_rate = (
        status_counts["unsupported"] + status_counts["contradicted"] + status_counts["unverifiable"]
    ) / claim_count
    claim_support_rate = status_counts["supported"] / claim_count
    claim_contradiction_rate = status_counts["contradicted"] / claim_count
    claim_unverifiable_rate = status_counts["unverifiable"] / claim_count

    if should_answer:
        grounded_answer_accuracy = (
            completeness >= 0.8
            and citation_recall >= 0.8
            and citation_precision >= 0.8
            and not forbidden
            and not abstained
            and unsupported_claim_rate == 0.0
        )
    else:
        grounded_answer_accuracy = abstained and not forbidden and claim_contradiction_rate == 0.0

    return {
        "id": case["id"],
        "failure_mode_category": case["failure_mode_category"],
        "difficulty": case["difficulty"],
        "should_answer": should_answer,
        "answer": answer,
        "abstained": abstained,
        "citation_precision": citation_precision,
        "citation_recall": citation_recall,
        "cited_chunks": cited,
        "required_evidence_chunks": sorted(required),
        "unknown_citations": sorted(cited_unknown),
        "abstention_correct": abstention_correct,
        "claims": claim_results,
        "claim_status_counts": status_counts,
        "claim_support_rate": claim_support_rate,
        "claim_contradiction_rate": claim_contradiction_rate,
        "claim_unverifiable_rate": claim_unverifiable_rate,
        "unsupported_claim_rate": unsupported_claim_rate,
        "answer_completeness": completeness,
        "grounded_answer_accuracy": grounded_answer_accuracy,
        "forbidden_keyword_hits": forbidden,
    }


def mean(values: list[float]) -> float:
    return statistics.fmean(values) if values else 0.0


def summarize(results: list[dict[str, Any]]) -> dict[str, Any]:
    answerable = [row for row in results if row["should_answer"]]
    abstain_cases = [row for row in results if not row["should_answer"]]
    by_category: dict[str, dict[str, float]] = {}

    for category in sorted({row["failure_mode_category"] for row in results}):
        rows = [row for row in results if row["failure_mode_category"] == category]
        by_category[category] = {
            "case_count": len(rows),
            "citation_precision": mean([row["citation_precision"] for row in rows]),
            "citation_recall": mean([row["citation_recall"] for row in rows]),
            "unsupported_claim_rate": mean([row["unsupported_claim_rate"] for row in rows]),
            "claim_support_rate": mean([row["claim_support_rate"] for row in rows]),
            "claim_contradiction_rate": mean([row["claim_contradiction_rate"] for row in rows]),
            "claim_unverifiable_rate": mean([row["claim_unverifiable_rate"] for row in rows]),
            "abstention_accuracy": mean([1.0 if row["abstention_correct"] else 0.0 for row in rows]),
            "grounded_answer_accuracy": mean([1.0 if row["grounded_answer_accuracy"] else 0.0 for row in rows]),
            "answer_completeness": mean([row["answer_completeness"] for row in rows]),
        }

    return {
        "case_count": len(results),
        "answerable_case_count": len(answerable),
        "abstain_case_count": len(abstain_cases),
        "citation_precision": mean([row["citation_precision"] for row in results]),
        "citation_recall": mean([row["citation_recall"] for row in results]),
        "unsupported_claim_rate": mean([row["unsupported_claim_rate"] for row in results]),
        "claim_support_rate": mean([row["claim_support_rate"] for row in results]),
        "claim_contradiction_rate": mean([row["claim_contradiction_rate"] for row in results]),
        "claim_unverifiable_rate": mean([row["claim_unverifiable_rate"] for row in results]),
        "abstention_accuracy": mean([1.0 if row["abstention_correct"] else 0.0 for row in results]),
        "grounded_answer_accuracy": mean([1.0 if row["grounded_answer_accuracy"] else 0.0 for row in results]),
        "answer_completeness": mean([row["answer_completeness"] for row in results]),
        "by_category": by_category,
    }


def print_summary(metrics: dict[str, Any]) -> None:
    print("\n## Grounded Generation Metrics Summary\n")
    print("| Metric | Value |")
    print("| --- | ---: |")
    for key in (
        "citation_precision",
        "citation_recall",
        "unsupported_claim_rate",
        "claim_support_rate",
        "claim_contradiction_rate",
        "claim_unverifiable_rate",
        "abstention_accuracy",
        "grounded_answer_accuracy",
        "answer_completeness",
    ):
        print(f"| {key.replace('_', ' ').title()} | {metrics[key]:.4f} |")

    print("\n## By Failure Mode\n")
    print("| Category | Cases | Citation Precision | Citation Recall | Unsupported Claim Rate | Claim Support | Contradicted | Unverifiable | Abstention Accuracy | Grounded Accuracy | Completeness |")
    print("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for category, row in metrics["by_category"].items():
        print(
            f"| {category} | {row['case_count']} | {row['citation_precision']:.4f} | "
            f"{row['citation_recall']:.4f} | {row['unsupported_claim_rate']:.4f} | "
            f"{row['claim_support_rate']:.4f} | {row['claim_contradiction_rate']:.4f} | "
            f"{row['claim_unverifiable_rate']:.4f} | "
            f"{row['abstention_accuracy']:.4f} | {row['grounded_answer_accuracy']:.4f} | "
            f"{row['answer_completeness']:.4f} |"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate grounded generation answers.")
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET, help="Synthetic benchmark JSONL.")
    parser.add_argument("--answers-jsonl", type=Path, help="Optional JSONL with id and answer/generated_answer fields.")
    parser.add_argument(
        "--mode",
        choices=("offline", "answers"),
        default="offline",
        help="offline runs evaluator_self_test with expected answers/citations; answers scores supplied model outputs.",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output JSON path.")
    args = parser.parse_args()

    if args.mode == "answers" and not args.answers_jsonl:
        raise SystemExit("--mode answers requires --answers-jsonl")
    evaluation_type = "evaluator_self_test" if args.mode == "offline" else "model_answer_evaluation"
    uses_expected_answer_as_prediction = args.mode == "offline"
    model_quality_signal = args.mode == "answers"
    if args.mode == "offline":
        print(f"WARNING: {EVALUATOR_SELF_TEST_DISCLOSURE}")

    started = time.perf_counter()
    cases = load_jsonl(args.dataset)
    supplied_answers = load_answers(args.answers_jsonl) if args.answers_jsonl else {}

    results: list[dict[str, Any]] = []
    for case in cases:
        answer = supplied_answers.get(case["id"]) if args.mode == "answers" else mock_answer(case)
        if answer is None:
            answer = "I do not have enough evidence in the provided documents to answer this safely."
        results.append(score_case(case, answer))

    metrics = summarize(results)
    metrics["latency_seconds"] = time.perf_counter() - started
    metrics["mode"] = evaluation_type
    metrics["cli_mode"] = args.mode
    metrics["evaluation_type"] = evaluation_type
    metrics["model_quality_signal"] = model_quality_signal
    metrics["uses_expected_answer_as_prediction"] = uses_expected_answer_as_prediction

    print_summary(metrics)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "metadata": {
            "dataset": str(args.dataset),
            "mode": evaluation_type,
            "cli_mode": args.mode,
            "evaluation_type": evaluation_type,
            "model_quality_signal": model_quality_signal,
            "uses_expected_answer_as_prediction": uses_expected_answer_as_prediction,
            "evaluated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "synthetic": True,
            "clinical_validation": "not_clinically_validated",
            "disclosure": EVALUATOR_SELF_TEST_DISCLOSURE if args.mode == "offline" else "",
            "note": "This benchmark is synthetic and intended for regression testing, not clinical validation.",
        },
        "metrics": metrics,
        "cases": results,
    }
    with args.output.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
    print(f"\nSaved detailed grounded-generation metrics to {args.output}")


if __name__ == "__main__":
    main()
